version: '3.8'

services:

  myapp:
    image: node:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /opt/node-test/src:/usr/src/app
    command: bash -c "cd /usr/src/app; node ."

